
export const ROLES = {
  ADMIN: 1,
  EMPLEADO: 2,
  CLIENTE: 3
};


export const PERMISOS = {
LISTAR_SALONES : [ROLES.ADMIN, ROLES.EMPLEADO, ROLES.CLIENTE],
CREAR_SALONES: [ROLES.ADMIN, ROLES.EMPLEADO],
ACTUALIZAR_SALONES: [ROLES.ADMIN, ROLES.EMPLEADO],
ELIMINAR_SALONES: [ROLES.ADMIN, ROLES.EMPLEADO],

LISTAR_SERVICIOS : [ROLES.ADMIN, ROLES.EMPLEADO, ROLES.CLIENTE],
CREAR_SERVICIOS: [ROLES.ADMIN, ROLES.EMPLEADO],
ACTUALIZAR_SERVICIOS: [ROLES.ADMIN, ROLES.EMPLEADO],
ELIMINAR_SERVICIOS : [ROLES.ADMIN, ROLES.EMPLEADO],

LISTAR_TURNOS : [ROLES.ADMIN, ROLES.EMPLEADO, ROLES.CLIENTE],
CREAR_TURNOS: [ROLES.ADMIN, ROLES.EMPLEADO],
ACTUALIZAR_TURNOS: [ROLES.ADMIN, ROLES.EMPLEADO],
ELIMINAR_TURNOS : [ROLES.ADMIN, ROLES.EMPLEADO],

LISTAR_USUARIOS : [ROLES.ADMIN],
CREAR_USUARIOS : [ROLES.ADMIN],
ACTUALIZAR_USUARIOS : [ROLES.ADMIN],
ELIMINAR_USUARIOS : [ROLES.ADMIN],

LISTAR_RESERVAS : [ROLES.ADMIN, ROLES.CLIENTE],
CREAR_RESERVAS : [ROLES.ADMIN, ROLES.CLIENTE],
ACTUALIZAR_RESERVAS : [ROLES.ADMIN],
ELIMINAR_RESERVAS : [ROLES.ADMIN],

GENERAR_REPORTE: [ROLES.ADMIN]

};



